// API
// Lists
export const GET_LISTS = 'GET_LISTS'
export const RECEIVE_LISTS = 'RECEIVE_LISTS'

// Item collections
export const GET_LIST_ITEMS = 'GET_LIST_ITEMS'
export const RECEIVE_LIST_ITEMS = 'RECEIVE_ITEMS'

// Items
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const REORDER_ITEM = 'REORDER_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const TOGGLE_ITEM = 'TOGGLE_ITEM'

// State
export const SET_NOW_EDITING = 'SET_NOW_EDITING'
export const SET_NOW_DRAGGING = 'SET_NOW_DRAGGING'
export const SET_NOW_DRAGGING_TO = 'SET_NOW_DRAGGING_TO'
export const SET_NOW_LOADING = 'SET_NOW_LOADING'
export const SET_ACITVE_LIST = 'SET_ACITVE_LIST'
export const SET_TODAY_BADGE_COUNT = 'SET_TODAY_BADGE_COUNT'
export const INCREMENT_TODAY_BADGE_COUNT = 'INCREMENT_TODAY_BADGE_COUNT'
export const DECREMENT_TODAY_BADGE_COUNT = 'DECREMENT_TODAY_BADGE_COUNT'

// Sort index
export const ADD_ITEM_INDEX = 'ADD_ITEM_INDEX'
export const EDIT_ITEM_INDEX = 'EDIT_ITEM_INDEX'
export const REORDER_ITEM_INDEX = 'REORDER_ITEM_INDEX'
export const REMOVE_ITEM_INDEX = 'REMOVE_ITEM_INDEX'
